# Generated by Django 5.2.4 on 2025-07-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('partial', 'Partial Payment'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('reconciled', 'Reconciled')], default='pending', max_length=20),
        ),
    ]
