# Generated by Django 5.2.4 on 2025-07-23 15:50

import django.db.models.deletion
import uuid
import common
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currency',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'name'], name='currency_code_44919f_idx')],
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DigitalWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_balance', models.BinaryField(default=common.ZeroBalanceConfig.encrypted_balance)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='walletservice.currency')),
                ('wallet_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet_owner', 'currency', 'is_default', 'is_active'], name='wallet_wallet__a72414_idx')],
                'unique_together': {('wallet_owner', 'currency')},
            },
        ),
    ]
