# Generated by Django 5.2.4 on 2025-08-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalwallet',
            old_name='_balance',
            new_name='encrypted_balance',
        ),
    ]
