# Generated by Django 5.2.4 on 2025-08-11 03:58

import common.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletservice', '0002_rename__balance_digitalwallet_encrypted_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('encrypted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('encrypted_reference', models.CharField(db_index=True, max_length=64)),
                ('encrypted_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='walletservice.digitalwallet')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='ledger_entr_created_c070e4_idx')],
            },
            bases=(common.encryption.EncryptedFieldsMixin, models.Model),
        ),
    ]
