# Generated by Django 5.2.4 on 2025-07-27 20:13

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('AUTH', 'Authentication'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROF_V', 'Profile View'), ('PROF_E', 'Profile Edit'), ('PAY', 'Payment'), ('ADMIN', 'Admin Action'), ('SYSTEM', 'System Action'), ('API', 'API Call'), ('ERROR', 'Error'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('flagged', models.BooleanField(default=False)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('headers', models.JSONField(default=dict)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_routable', models.BooleanField(default=False)),
                ('is_cloud', models.BooleanField(default=False)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_tor', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('coordinates', models.CharField(blank=True, max_length=50)),
                ('asn', models.CharField(blank=True, max_length=50)),
                ('isp', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('is_mobile', models.BooleanField(blank=True, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('is_tablet', models.BooleanField(blank=True, null=True)),
                ('is_pc', models.BooleanField(blank=True, null=True)),
                ('is_bot', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='tracking_ac_user_id_3dfb26_idx'), models.Index(fields=['ip_address', '-timestamp'], name='tracking_ac_ip_addr_55e691_idx'), models.Index(fields=['type', '-timestamp'], name='tracking_ac_type_48fa93_idx'), models.Index(fields=['-timestamp', 'status'], name='tracking_ac_timesta_6894e2_idx')],
            },
        ),
    ]
