-- Role: dbadmin
-- DROP ROLE IF EXISTS dbadmin;

CREATE ROLE dbadmin WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:zDPVckgU+oENiR2QbdkUPg==$OZW7J8eHJD2mci47wnwpw4i28HxTxaw2I2KHytyZypA=:vT6eoPHuZE5rhKh/RKJ4jmey0V5h+NQ0GvbqtLC60OA=';