# Generated by Django 5.2.4 on 2025-07-23 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('codename', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('USER', 'User Management'), ('TRANSACTION', 'Transactions'), ('LOAN', 'Loan Operations'), ('REPORT', 'Reporting'), ('SYSTEM', 'System Administration')], default='SYSTEM', max_length=32)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('ALL', 'ALL')], default='ALL', max_length=6)),
                ('is_sensitive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permission',
                'ordering': ['name', 'category', 'method'],
                'indexes': [models.Index(fields=['codename'], name='permission_codenam_ada6cd_idx'), models.Index(fields=['category'], name='permission_categor_593940_idx'), models.Index(fields=['method'], name='permission_method_66677e_idx')],
                'unique_together': {('codename', 'method')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Senior'), (4, 'Administrator'), (5, 'System')], default=1)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level'], name='role_level_f0a914_idx'), models.Index(fields=['is_default'], name='role_is_defa_fd0094_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='rbac.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permission',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_role',
                'ordering': ['user', '-assigned_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_role_user_id_48b509_idx'), models.Index(fields=['expires_at'], name='user_role_expires_8ea876_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
