# Generated by Django 5.2.4 on 2025-07-23 15:50

import django.db.models.deletion
import common
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('walletservice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(editable=False, max_length=24, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('INTERNAL_TRANSFER', 'Send Money'), ('EXTERNAL_TRANSFER', 'Send to M-Pesa / Bank'), ('INTERNAL_REQUEST', 'Request Money'), ('EXTERNAL_REQUEST', 'Request from M-Pesa / Bank'), ('CURRENCY_EXCHANGE', 'Swap Currencies'), ('TOPUP', 'Add Funds'), ('WITHDRAW', 'Withdraw Funds'), ('REFUND', 'Get a Refund'), ('BUY_AIRTIME', 'Top Up Airtime')], max_length=50)),
                ('_amount', models.BinaryField(default=common.DefaultConfig.balance)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('SUCCESS', 'Success'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('action', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('CANCEL', 'Cancel'), ('DECLINE', 'Decline')], max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('requested_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2p_transfer_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requesting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2p_transfer_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund Transfer Request',
                'verbose_name_plural': 'Fund Transfer Requests',
                'db_table': 'fund_transfer_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(editable=False, max_length=36, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('INTERNAL_TRANSFER', 'Send Money'), ('EXTERNAL_TRANSFER', 'Send to M-Pesa / Bank'), ('INTERNAL_REQUEST', 'Request Money'), ('EXTERNAL_REQUEST', 'Request from M-Pesa / Bank'), ('CURRENCY_EXCHANGE', 'Swap Currencies'), ('TOPUP', 'Add Funds'), ('WITHDRAW', 'Withdraw Funds'), ('REFUND', 'Get a Refund'), ('BUY_AIRTIME', 'Top Up Airtime')], max_length=50)),
                ('_amount', models.BinaryField(default=common.DefaultConfig.balance)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('transaction_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('receiver_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='walletservice.digitalwallet')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='paymentservice.TransactionRecord')),
                ('sender_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='walletservice.digitalwallet')),
                ('request_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paymentservice.RequestedTransaction')),
            ],
            options={
                'verbose_name': 'Fund Transaction Record',
                'verbose_name_plural': 'Fund Transaction Records',
                'db_table': 'fund_transaction_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReversalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('AUTO_REVERSED', 'AUTO_REVERSED')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversal_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reversal_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_requests', to='paymentservice.TransactionRecord')),
            ],
            options={
                'verbose_name': 'Reversal Request',
                'verbose_name_plural': 'Reversal Requests',
                'db_table': 'reversal_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='RequestedTransaction',
            index=models.Index(fields=['requesting_user', 'requested_user', 'status'], name='fund_transf_request_fd2f87_idx'),
        ),
        migrations.AddIndex(
            model_name='TransactionRecord',
            index=models.Index(fields=['sender_wallet', 'receiver_wallet', 'status'], name='fund_transa_sender__8c3600_idx'),
        ),
    ]
