# Generated by Django 5.2.4 on 2025-07-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='TransactionRecord',
            name='fraud_checked',
            field=models.BooleanField(default=False),
        ),
    ]
