# Generated by Django 5.2.4 on 2025-08-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentservice', '0002_fundtransactionrecord_fraud_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedtransaction',
            old_name='_amount',
            new_name='encrypted_amount',
        ),
        migrations.RenameField(
            model_name='transactionrecord',
            old_name='_amount',
            new_name='encrypted_amount',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='reversal_of',
        ),
        migrations.DeleteModel(
            name='ReversalRequest',
        ),
    ]
