# Generated by Django 5.2.4 on 2025-07-24 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDeviceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('os_name', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('device_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=100)),
                ('network_carrier', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('first_used', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication Device Profile',
                'verbose_name_plural': 'Authentication Device Profiles',
                'db_table': 'auth_device_profile',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['ip_address', 'last_used'], name='auth_device_ip_addr_78ccd8_idx'), models.Index(fields=['user', 'is_trusted'], name='auth_device_user_id_8565a4_idx')],
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
    ]
