# Generated by Django 5.2.4 on 2025-07-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0002_authdeviceprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthDeviceProfile',
        ),
    ]
