# Generated by Django 5.2.4 on 2025-08-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0003_delete_authdeviceprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='_otp',
            new_name='encrypted_otp',
        ),
    ]
