# Generated by Django 5.2.4 on 2025-07-23 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rate Snapshot',
                'verbose_name_plural': 'Rate Snapshots',
                'db_table': 'rate_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(editable=False, max_length=24, null=True, unique=True)),
                ('transaction_type', models.CharField(default='CURRENCY_EXCHANGE', max_length=50)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PROCESSING', max_length=50)),
                ('source_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('source_amount', models.DecimalField(decimal_places=6, max_digits=30)),
                ('converted_amount_with_fee', models.DecimalField(decimal_places=6, max_digits=30)),
                ('base_exchange_rate', models.DecimalField(decimal_places=6, max_digits=30)),
                ('platform_exchange_rate', models.DecimalField(decimal_places=6, max_digits=30)),
                ('charged_amount', models.DecimalField(decimal_places=6, max_digits=30)),
                ('charged_amount_currency', models.CharField(max_length=3, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional info about the exchange', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forex_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency Exchange Record',
                'verbose_name_plural': 'Currency Exchange Records',
                'db_table': 'currency_exchange_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'source_currency', 'target_currency'], name='currency_ex_user_id_f1327c_idx')],
            },
        ),
    ]
