from django.conf import settings

STATEMENT_PERIOD_DAYS = 180

APP_NAME = settings.APP_NAME
APP_VERSION = settings.APP_VERSION
EMAIL_REPLY_TO = settings.EMAIL_REPLY_TO
COPYRIGHT_YEAR = settings.COPYRIGHT_YEAR
FRONTEND_PRODUCTION_URL = settings.FRONTEND_PRODUCTION_URL

APP_NAME_VERSION = f"{APP_NAME} v{APP_VERSION}"
