# Generated by Django 5.2.4 on 2025-07-23 15:53

import django.db.models.deletion
import userservice.models.customer.customer
import uuid
from django.conf import settings
from django.db import migrations, models
from common import DefaultConfig


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('selfie_image', models.BinaryField(blank=True, null=True)),
                ('is_selfie_image_verified', models.BooleanField(default=False)),
                ('id_image_front', models.BinaryField(blank=True, null=True)),
                ('is_id_image_front_verified', models.BooleanField(default=False)),
                ('id_image_back', models.BinaryField(blank=True, null=True)),
                ('is_id_image_back_verified', models.BooleanField(default=False)),
                ('address_proof_image', models.BinaryField(blank=True, null=True)),
                ('is_address_proof_image_verified', models.BooleanField(default=False)),
                ('_id_type', models.BinaryField(blank=True, null=True)),
                ('_id_number', models.BinaryField(blank=True, null=True)),
                ('_country', models.BinaryField(blank=True, null=True)),
                ('_region_state', models.BinaryField(blank=True, null=True)),
                ('_city', models.BinaryField(blank=True, null=True)),
                ('_postal_code', models.BinaryField(blank=True, null=True)),
                ('_postal_address', models.BinaryField(blank=True, null=True)),
                ('_address', models.BinaryField(blank=True, null=True)),
                ('_next_of_kin_name', models.BinaryField(blank=True, null=True)),
                ('_next_of_kin_relationship', models.BinaryField(blank=True, null=True)),
                ('_next_of_kin_contact', models.BinaryField(blank=True, null=True)),
                ('_verification_status', models.BinaryField(blank=True, null=True)),
                ('_customer_verified', models.BinaryField(default=DefaultConfig.unverified)),
                ('_remarks', models.BinaryField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_customer', to='userservice.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Verification',
                'verbose_name_plural': 'Customer Verifications',
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'user'], name='customers_created_074a14_idx')],
            },
        ),
    ]
