# Generated by Django 5.2.4 on 2025-07-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biometric_option_chosen',
        ),
    ]
