# Generated by Django 5.2.4 on 2025-08-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0003_remove_user_biometric_option_chosen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='_address',
            new_name='_residential_address',
        ),
    ]
