# Generated by Django 5.2.4 on 2025-08-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0004_rename__address_customer__residential_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='_city',
            new_name='encrypted_city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_country',
            new_name='encrypted_country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_customer_verified',
            new_name='encrypted_customer_verified',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_id_number',
            new_name='encrypted_id_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_id_type',
            new_name='encrypted_id_type',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_next_of_kin_contact',
            new_name='encrypted_next_of_kin_contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_next_of_kin_name',
            new_name='encrypted_next_of_kin_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_next_of_kin_relationship',
            new_name='encrypted_next_of_kin_relationship',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_postal_address',
            new_name='encrypted_postal_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_postal_code',
            new_name='encrypted_postal_code',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_region_state',
            new_name='encrypted_region_state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_remarks',
            new_name='encrypted_remarks',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_residential_address',
            new_name='encrypted_residential_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='_verification_status',
            new_name='encrypted_verification_status',
        ),
    ]
